name: upcode_ci
description: A collection of tools used by Upcode team
version: 0.10.3
repository: https://github.com/long1eu/upcode_ci
executables:
  upcode:

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  path: ^1.8.3
  pub_semver: ^2.1.4
  googleapis: ^11.4.0
  googleapis_beta: ^8.0.0
  googleapis_auth: ^1.4.1
  uuid: ^4.2.1
  intl: ^0.18.1
  args: ^2.4.2
  xml: ^6.4.2
  http: ^0.13.0
  http_multi_server: ^3.2.1
  xml2json: ^6.2.1
  yaml: ^3.1.2
  protobuf: ^3.1.0
  fixnum: ^1.1.0
  collection: ^1.18.0
  grpc: ^3.2.4
  strings: ^2.0.3